version: '3'  # Specifies the version of Docker Compose file format, '3' is the latest as of my knowledge cutoff in September 2021.
name: mothership

services:  # Top-level key that specifies each service (i.e., container) that makes up the app.

  redis:  # Defines a service named "redis".
    image: 'redis:latest'  # Specifies the Docker image to use for this service. The image is "redis" and the tag is "alpine", which is a minimal version.
    ports:
      - '6379:6379'
    healthcheck: # Specifies a health check to perform to determine if the container is healthy.
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  conductor:  # Defines a service named "conductor".
    build: 
      context: .
      dockerfile: docker/Dockerfile.conductor
    ports:
      - 3000:3000
      - 4321:4321
      - 1235:1235
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
      - type: volume
        source: shared
        target: /usr/src/app/shared
    command: ["npm", "run", "start_insideDocker"]
    depends_on:  # Expresses dependency between services, which determines the order of service startup.
      redis:  # "node_app" service depends on the "redis" service.
        condition: service_healthy  # The "redis" service must be healthy and running before starting the conductor service
      # - python_sidecar

  # python_sidecar:  # Defines a service named "python_sidecar".
  #   build: 
  #     context: .
  #     dockerfile: docker/Dockerfile.python_sidecar
  #   volumes:
  #     - type: volume
  #       source: shared
  #       target: /usr/src/app/shared
  #   command: ["python3", "-u", "index.py"]
  #   depends_on:
  #     - redis
  #   runtime: nvidia  # Specifies the Docker container's runtime. "nvidia" is necessary for leveraging the host's GPU.

volumes:  # Top-level key that defines named volumes.
  shared:  # Defines a named volume called "shared". This volume can be used by any service to share data.
  nodemodules:
    external: true
