
FROM python:3.7-slim

# Sets the working directory in the Docker image.
WORKDIR /usr/src/app

# Copies requirements.txt to the Docker image.
COPY src/sidecar/requirements.txt ./

# Installs the Python dependencies in the Docker image.
RUN pip install --no-cache-dir -r requirements.txt

# Copies the rest of the application code to the Docker image.
COPY src/sidecar/ .
