# The base image for this Dockerfile, it's a Node.js image that includes Node.js
# and npm.
FROM node:19

# Sets the working directory in the Docker image. All the following instructions
# (COPY, RUN, CMD) will be run from this directory.
WORKDIR /usr/src/app