// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyBqHlPxaZZUfOZHkRQcmY2jOToU-egpCmU",
  authDomain: "arkhe-project.firebaseapp.com",
  projectId: "arkhe-project",
  storageBucket: "arkhe-project.appspot.com",
  messagingSenderId: "112854514585",
  appId: "1:112854514585:web:10637445ec78b31ea37108"
};

// Initialize Firebase
const firebaseApp = initializeApp(firebaseConfig);

function writeData(alg, imgData, time) {
  alg = JSON.stringify(alg);
  const db = getDatabase();
  const Ref = ref(db, "algebraData");
  const newRef = push(Ref, {
    alg,
    imgData,
    time
  });
  // the unique ID generated by Firebase that we could use later to reference or change this value
  //console.log("newRef",newRef.key);
  console.log(alg);
}
function update() {
  //console.log(popular);
  const db = getDatabase();
  const Ref = ref(db, "algebraData");
  function dataChanged(snapshot) {
    let data = snapshot.val();
    let key = Object.keys(data);
  }
  onValue(Ref, dataChanged);
}
//END FIREBASE

export { writeData, update };
